#pragma once
#include "sdkconfig.h"

#define CFG_WIFI_SSID          CONFIG_HERVOICE_WIFI_SSID
#define CFG_WIFI_PASSWORD      CONFIG_HERVOICE_WIFI_PASSWORD
#define CFG_SERVER_HOST        CONFIG_HERVOICE_SERVER_HOST
#define CFG_SERVER_PORT        CONFIG_HERVOICE_SERVER_PORT
#define CFG_DEVICE_ID          CONFIG_HERVOICE_DEVICE_ID
#define CFG_SAMPLE_RATE        CONFIG_HERVOICE_SAMPLE_RATE
#define CFG_FRAME_SAMPLES      CONFIG_HERVOICE_AUDIO_FRAME_SAMPLES
#define CFG_WAKE_THRESHOLD     CONFIG_HERVOICE_WAKE_THRESHOLD
#define CFG_VAD_START_THR      CONFIG_HERVOICE_VAD_START_THRESHOLD
#define CFG_VAD_STOP_THR       CONFIG_HERVOICE_VAD_STOP_THRESHOLD
#define CFG_VAD_SILENCE_MS     CONFIG_HERVOICE_VAD_SILENCE_TIMEOUT_MS
#define CFG_MAX_SESSION_MS     CONFIG_HERVOICE_MAX_SESSION_DURATION_MS
#define CFG_TCP_RETRIES        CONFIG_HERVOICE_TCP_RETRY_COUNT

/* Derived */
#define CFG_RING_BUF_SAMPLES   (CFG_SAMPLE_RATE / 2)   /* 500ms ring buffer */
#define CFG_PLAYBACK_CHUNK     512
